name: CheckPython2

on: [pull_request]

jobs:
  clean-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ma-sadeghi/ruff-action@feature/changed-only
        with:
          changed-files: "true"
